### PR TITLE
Upgrade to 3.6.1~ynh1

### LINKED ISSUE #53: You are 19 releases behind the latest version available. You should update your instance.
Monica tells me: You are 19 releases behind the latest version available. You should update your instance.

Steps to reproduce: Install yunohost-app "Monica".

You should consider a upgrade for this app.

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Fix #53*

## Solution

- *Upgrade to 3.6.1~ynh1*
- Require YunoHost Bullseye as php7.3-redis is not compatible with php7.4-redis

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)
- [x] Bullseye released

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Review by alexAubin — APPROVED** [review]
Super quick review, LGTM, didnt check why CI is failing to upgrade from old versions

**Comment by yalh76** [comment]
Waiting bullseye as php7.4-redis is not compatible with php7.3-redis

**Comment by yalh76** [comment]
!testme !bullseyetestme

**Comment by yalh76** [comment]
!testme

**Pull request merged**
